"""added prints table

Revision ID: 68853d4c9d2c
Revises: 86085e44f737
Create Date: 2024-04-03 19:59:57.526641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68853d4c9d2c'
down_revision = '86085e44f737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_pages', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('printed_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['printed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prints_printed_by_id'), ['printed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prints_time_stamp'), ['time_stamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_column('fs_uniquifier')

    with op.batch_alter_table('prints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prints_time_stamp'))
        batch_op.drop_index(batch_op.f('ix_prints_printed_by_id'))

    op.drop_table('prints')
    # ### end Alembic commands ###
